
name: Node.js CI

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_call:  # הופך את ה-workflow ל-Reusable
    inputs:
      node-versions:
        description: 'Node.js versions to run the matrix on'
        required: false
        default: ["18", "20", "22"]
        type: array

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ inputs.node-versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: ${{ inputs.node-versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    strategy:
      matrix:
        node-version: ${{ inputs.node-versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build